source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'

pod 'Cent'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

pod 'FontAwesomeKit'

pod 'GooglePlacesAutocomplete'

pod 'HanekeSwift'

pod 'MaterialKit'

pod 'ObjectMapper'

pod 'PureLayout'

pod 'Socket.IO-Client-Swift'

pod 'SwiftyJSON'

pod 'TTRangeSlider'
